export * from './character.interface'
export * from './location.interface'
export * from './episode.interface'
export * from './info.interface'
export * from './pagination.interface'
export * from './tableColumn.interface'
